Daily Update
220516-Java-Angular-Enterprise/P3_Trailmates_Front_End pull request #52
Opened 2022-07-14 22:47 UTC by HaibunisCool

- Updated user profile
- Trail Page
- Switched services to revature.Trailmates

2022-07-14 22:47 UTC, HaibunisCool commented
- Also finished notifications

2022-07-14 23:56 UTC, MattB120 requested changes

2022-07-14 23:56 UTC, MattB120 commented on Trailmates/src/app/profile-page/trail-history/trail-history.component.html
> +<<<<<<< HEAD
Merge conflict remains

2022-07-14 23:56 UTC, MattB120 commented on Trailmates/src/app/profile-page/trail-history/trail-history.component.html
> +>>>>>>> f5479050a005972bca3c7e5891ab31b41bab571b
Merge conflict remains

2022-07-14 23:56 UTC, MattB120 commented on Trailmates/src/app/services/friend.service.ts
> +  url: string = 'http://trailmates-env.us-east-1.elasticbeanstalk.com/TrailMates/friends/'
Still old url should be```https://revature.trailmates.net/TrailMates/```

2022-07-15 13:16 UTC, labrecquemegan approved these changes

2022-07-15 14:05 UTC, MattB120 approved these changes

2022-07-15 14:07 UTC, merged